import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/widgets/header";
import { Sidebar } from "@/widgets/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} flex flex-col h-screen`}>
                <Header className="flex-grow-0 bg-gray-800 p-4" />

                <div className="flex">
                    <Sidebar className="relative bg-gray-800 p-2 h-[90vh] mt-2 flex-grow-0 justify-start flex-col gap-5 rounded-md" />
                    <main className="flex-grow">{children}</main>
                </div>
            </body>
        </html>
    );
}
